### ISSUE TITLE
Cura crashes when trying to upload

### ISSUE THREAD

**Issue by Jasonpgr44** [Kriechi/Cura-DuetRRFPlugin#11]
I'm fairly new to all this, so it might be something on my end, but I can't figure out what I could possibly be doing wrong. I'm running Cura 3.3.1 on mac os x 10.13.4 and I've got the plugin installed, it seems to be able to find and connect to my duet wifi with no problem, I select upload to duet and print, and cura closes down entirely and the file never ends up transferring over to the duet. If someone can walk me through to create/find a log I'd be happy to upload one, I'm just not really sure what a log is or how to find one. I just know that's the first thing people always ask for when presented with an issue.

**Comment by Kriechi** [comment]
The log, or "log file", is a text document with many many lines of messages that help developers to understand what is happening in a program.

You can find the Cura log file in `C:\Users\<username>\AppData\Roaming\cura\3.3\cura.log`.
The file is probably very big, so maybe delete it, then start Cura and try to print to your Duet. Once Cura crashes, you can copy the log file and upload its contents here.
