### ISSUE TITLE
Unable to load into CURA 4.0

### ISSUE THREAD

**Issue by PatrikTheDev** [Kriechi/Cura-DuetRRFPlugin#16]
Hi, I installed the plugin via the marketplace but it did not load into the UI, so I dug into the files and not only it was nested, in the plugin.json there was max Cura version 3.6, so I bumped it up to 4.0 but still nothing, what is going on?

**Comment by Kriechi** [comment]
Unless they changed something again in the last beta, it should work.
I tested it with the Cura-preview a few weeks ago.

Do you get an error message or other entries in the `cura.log` file?

**Comment by PatrikTheDev** [comment]
I don't know, can you try it with the 4.0?

**Comment by Kriechi** [comment]
I did. It worked.

Please check your `cura.log` file and look for errors or other indication on why the plugin does not load. Also, try reinstalling via Marketplace - the version it downloads might be different on Cura 4.0.

**Comment by PatrikTheDev** [comment]
Fixed: I had to bump up that number and change the API to 6

**Comment by PatrikTheDev** [comment]
Please fix it so that this is like this by default

**Comment by PatrikTheDev** [comment]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/25883885/50729461-50a0c680-113a-11e9-9e99-a6e5f88bf90d.png">
oh shit, this doesn't look good

**Comment by Kriechi** [comment]
The version in the Marketplace should already have the correct version numbers
I pushed the same changes to git-master now as well.
