### ISSUE TITLE
Acceptable IP Addresses

### ISSUE THREAD

**Issue by bmalcheski** [Kriechi/Cura-DuetRRFPlugin#17]
Not all IP addresses are 192.x.x.xxx. For example, mine are 10.0.0.xxx. They can certainly differ more. Can this be changed to support different IP addresses more easily?

**Comment by Kriechi** [comment]
Where do you see this as a problem?
I‘m not aware of any limitations enforced by the plugin...

Do you have an error message or reproducible test case that demonstrates the issue you are describing?

**Comment by bmalcheski** [comment]
I now realize it was because I had deleted the "https://" that caused the
error. When I first got the error, I was under the impression it was
checking the values in the IP address. My apologies.
