### ISSUE TITLE
Cura 3.6 incompatible API

### ISSUE THREAD

**Issue by greenaar** [Kriechi/Cura-DuetRRFPlugin#18]
Seen in the logs:

2019-02-04 13:35:06,682 - WARNING - [MainThread] UM.PluginRegistry.loadPlugin [402]: Plugin DuetRRFPlugin uses an incompatible API version, ignoring

This is against 1.0.3, and head.  As such, the plugin is not loaded.

**Comment by Kriechi** [comment]
API versioning is unfortunately fundamentally broken in Cura 3.6 and 4.0 with the transitioning to a new system.  Please install v1.0.2 from source or the release package. There was no functional change in v1.0.3.

**Comment by greenaar** [comment]
Thank you!
