### ISSUE TITLE
duetrrfplugin loads but cant see printer

### ISSUE THREAD

**Issue by GrahamPort** [Kriechi/Cura-DuetRRFPlugin#23]
I have loaded the plugin and set up a new printer. I can see the printer with a web brouser but not in Cura I am running W10 and have Cura 4.4.1 running. What am i doing wrong

**Comment by Kriechi** [comment]
Did you follow the configuration instructions and screenshots in the Readme file?
Do you see the new button with your printer's name when you have a model loaded and sliced?

**Comment by GrahamPort** [comment]
Oppps. i did not know i had to load a model and slice it before i could see my printer. Sorry. All good now

**Comment by GrahamPort** [comment]
Does it work in Cura 4.5? shall i upgrade?

**Comment by Kriechi** [comment]
Yes it should - if not please open a new issue with your problem description.
