### ISSUE TITLE
Plugin missing from marketplace

### ISSUE THREAD

**Issue by ComedianTF2** [Kriechi/Cura-DuetRRFPlugin#25]
I just reinstalled Cura, and was looking for the plugin at the Cura marketplace, but it seems to be missing. Will it return, or should I install it via the github?

**Comment by Kriechi** [comment]
I can still see it in a recent Cura 4.6.1 on macOS.
<img width="624" alt="Screenshot 2020-05-18 at 18 15 39" src="https://user-images.githubusercontent.com/114300/82235904-a0e58680-9933-11ea-90e9-65fc986557fb.png">

**Comment by ComedianTF2** [comment]
I have discovered what the issue was. I had somehow installed Cura 4.5 instead of Cura 4.61, and not noticed it.

And it didn't show up for 4.5, but once I updated to 4.6.1 it worked
