### ISSUE TITLE
Cura 4.7 and 4.8 (linux appimage) crash some time after starting a print on duet2wifi

### ISSUE THREAD

**Issue by CopterFail** [Kriechi/Cura-DuetRRFPlugin#33]
The plugin is 1.0.11. 
The crash occours some time (15s..x minutes) after the print was started and cura opened a browser window. 
Cura disappears from the task bar.

**Comment by Kriechi** [comment]
Please follow the bug report template and provide the necessary information:
https://github.com/Kriechi/Cura-DuetRRFPlugin/issues/new/choose
