### ISSUE TITLE
DuetRRF plugin not available in Marketplace(4.9.1/4.10)

### ISSUE THREAD

**Issue by wolfgangmauer** [Kriechi/Cura-DuetRRFPlugin#37]
The great!!! Duet RRF plugin is not available in the Marketplace(4.9.1/4.10) :-(

**Comment by Kriechi** [comment]
Does this work for you?
https://marketplace.ultimaker.com/app/cura/plugins/thomas_kriechbaumer/DuetRRFPlugin

**Comment by Kriechi** [comment]
Also shows up just fine in Cura 4.10.0 on macOS, see this screenshot I just took with an empty/fresh/clean Cura profile:
<img width="736" alt="Screenshot 2021-07-03 at 19 14 02" src="https://user-images.githubusercontent.com/114300/124362033-e8f86300-dc32-11eb-98e0-bc30f4d57904.png">

**Comment by wolfgangmauer** [comment]
Sorry, it shows up in the Marketplace, but with 4.8 it looks like this
![grafik](https://user-images.githubusercontent.com/27953724/124362193-cdda2300-dc33-11eb-9af7-6828adab27fa.png)
with 4.9.1/4.10 the menu is not availible
![grafik](https://user-images.githubusercontent.com/27953724/124362237-0d087400-dc34-11eb-9c55-32f1848f575e.png)
And after slicing i only get
![grafik](https://user-images.githubusercontent.com/27953724/124362277-4345f380-dc34-11eb-80bb-95bcfb5c874d.png)

**Comment by Kriechi** [comment]
1. The plugin settings moved to the "Manage Printer" section a while ago
2. The menu item should still be there - and it should tell you about the move.
3. You might have to reconfigure your printer settings if you clicked-away or deleted the old settings without reading the upgrade instructions.

Please check in the Marketplace again under "installed" plugins - maybe it is disabled?

**Comment by wolfgangmauer** [comment]
Sorry for "spam", the plugin was disabled
