### ISSUE TITLE
feature request: default path for upload

### ISSUE THREAD

**Issue by pkoevesdi** [Kriechi/Cura-DuetRRFPlugin#38]
Since upload to subfolders works (see #26), it would be very handy to have an option to set a default subfolder (prefilled with in the upload dialog) or the folder, from which the paths entered in the upload dialog is relative to.

**Comment by fieldOfView** [comment]
You can do this with the Printjob Naming plugin which is available from the Marketplace. It will let you set a custom prefix and postfix, but also a path (for selected output devices, including the DuetRRF plugin).

**Comment by pkoevesdi** [comment]
Ok, thanks, that's doing it.
