### ISSUE TITLE
Cura 5.0 support

### ISSUE THREAD

**Issue by nallath** [Kriechi/Cura-DuetRRFPlugin#42]
Since I was reviewing your plugin, I also did a quick check if you were still using QtControls 1.0, since that will no longer be supported in the next Cura release (5.0) due to the upgrade to Qt6. 

I noticed that you still use controls 1.0, but luckily the interface is relatively simple. If you upgrade them to controls 2.0, it will still be backwards compatible.

**Comment by Kriechi** [comment]
@nallath thanks for the heads-up! I briefly checked the upgrade path, and I got it mostly working, but the UI looks quite different... buttons are larger, textfields higher and with more padding, default button flag is missing, mouse-drag-to-select-text not working, text selection color not readable...

Do you have any pointers to upgrade docs or how did you handle this for Uranium+Cura?

**Comment by Kriechi** [comment]
Old / Controls 1.0:
<img width="400" alt="Screenshot 2022-02-15 at 20 52 13" src="https://user-images.githubusercontent.com/114300/154138461-48e52adc-d1d1-433d-a2a3-b2e8642c0a92.png">

New / Controls 2.0:
<img width="400" alt="Screenshot 2022-02-15 at 20 52 49" src="https://user-images.githubusercontent.com/114300/154138468-2dc056a9-6c77-4930-853d-f550961c0d4b.png">

**Comment by nallath** [comment]
Yeah, there will be some visual changes, you really cant avoid that. The controls 2.0 no longer have system styling. 

We are currently working on making sure that there are re-usable components that will have the standard Cura style (see: https://github.com/Ultimaker/Cura/pull/10788), but those will obviously not be back ported for older versions.

As for customizing the textfield, you can find some more info about it here https://doc.qt.io/qt-5/qtquickcontrols2-customize.html#customizing-textfield

**Comment by Kriechi** [comment]
fixed with the last release.
