### ISSUE TITLE
Printer not showing to add

### ISSUE THREAD

**Issue by Monroe07** [Kriechi/Cura-DuetRRFPlugin#44]
Cura 5.0
Board: Duet 2 WiFi (2WiFi)
Firmware: RepRapFirmware for Duet 2 WiFi/Ethernet 3.4.0 (2022-03-15)
Duet WiFi Server Version: 1.26 
Windows 11
Ultimaker 3 already added in Cura (Don't know if that detail is relevant)

Plugin added via Marketplace.

When adding the printer in Cura, the printer does not show up in "Printer" section to "activate". No option in Cura discovers the printer. No "Connect Duet RepRapFirmware" option listed.

![image](https://user-images.githubusercontent.com/20032550/171484380-28ec1ca4-4ac4-40d3-ad14-3c83e37fa463.png)

**Comment by Kriechi** [comment]
Can you post a screenshot?
You need to add a non-Ultimaker printer - usually using the "custom" category. If it is your only printer, you don't need to "activate" it. Simply select it in the list, and the config button should show up.

**Comment by Monroe07** [comment]
I got it working. So to clarify, you have to select the "custom" section within the "Add a non-networked printer" section, which is counter intuitive when the purpose is to add a networked [3rd party] printer( I know, not your lane ). Should probably add a note in the documentation about doing that by either adding a printer using the main screen printer selection drop-down and choosing a custom "non-networked" option, or doing the same selection within the preferences.

**Comment by Kriechi** [comment]
There is already this section in the README:
> **Do NOT try to add a new "networked printer"!** This is only for Ultimaker printers.

If you have any suggestion to improve this even further, I'm happy to merge a PR!
