### ISSUE TITLE
On windows 64 bit the Plugin fail to work 

### ISSUE THREAD

**Issue by YaronSoffer** [Kriechi/Cura-DuetRRFPlugin#46]
**Describe the bug**
When loading in Cura 50 the plugin fails to load .
Was working in prev versions.

**To Reproduce**
1. Check the master or install through Cura 
2. Cura will load specifying the plugin fail to load - suggesting to remove it 

**Expected behavior**
Plugin Loading 

**Version Information**
 - Operating System: Windows 10
 - Cura Version: 5.0.0]
 - Cura-DuetRRF Plugin Version and Installation: git-master ( and tried the through Cura)
 - Duet RepRapFirmware Version: 

M122
=== Diagnostics ===
RepRapFirmware for Duet 2 WiFi/Ethernet version 3.4.0 (2022-03-15 18:58:31) running on Duet WiFi 1.02 or later
Board ID: 08DJM-9178L-L4MSJ-6J1FA-3S06S-T83LN
Used output buffers: 3 of 24 (24 max)
=== RTOS ===
Static ram: 23868
Dynamic ram: 74668 of which 184 recycled
Never used RAM 13360, free system stack 180 words
Tasks: NETWORK(ready,12.4%,234) HEAT(notifyWait,0.0%,316) Move(notifyWait,0.0%,364) MAIN(running,87.5%,416) IDLE(ready,0.0%,30), total 100.0%
Owned mutexes: WiFi(NETWORK)
=== Platform ===
Last reset 00:52:44 ago, cause: power up
Last software reset time unknown, reason: User, GCodes spinning, available RAM 9616, slot 1
Software reset code 0x0003 HFSR 0x00000000 CFSR 0x00000000 ICSR 0x0041f000 BFAR 0xe000ed38 SP 0x00000000 Task MAIN Freestk 0 n/a
Error status: 0x04
Aux0 errors 0,0,0
Step timer max interval 0
MCU temperature: min 22.1, current 26.9, max 27.9
Supply voltage: min 23.9, current 24.1, max 24.3, under voltage events: 0, over voltage events: 0, power good: yes
Heap OK, handles allocated/used 0/0, heap memory allocated/used/recyclable 0/0/0, gc cycles 0
Events: 0 queued, 0 completed
Driver 0: standstill, SG min n/a
Driver 1: standstill, SG min n/a
Driver 2: standstill, SG min n/a
Driver 3: standstill, SG min n/a
Driver 4: standstill, SG min n/a
Driver 5: 
Driver 6: 
Driver 7: 
Driver 8: 
Driver 9: 
Driver 10: 
Driver 11: 
Date/time: 2022-08-02 12:29:34
Cache data hit count 4294967295
Slowest loop: 9.76ms; fastest: 0.19ms
I2C nak errors 0, send timeouts 0, receive timeouts 0, finishTimeouts 0, resets 0
=== Storage ===
Free file entries: 10
SD card 0 detected, interface speed: 20.0MBytes/sec
SD card longest read time 3.7ms, write time 0.0ms, max retries 0
=== Move ===
DMs created 83, segments created 0, maxWait 0ms, bed compensation in use: none, comp offset 0.000
=== MainDDARing ===
Scheduled moves 0, completed 0, hiccups 0, stepErrors 0, LaErrors 0, Underruns [0, 0, 0], CDDA state -1
=== AuxDDARing ===
Scheduled moves 0, completed 0, hiccups 0, stepErrors 0, LaErrors 0, Underruns [0, 0, 0], CDDA state -1
=== Heat ===
Bed heaters 0 -1 -1 -1, chamber heaters -1 -1 -1 -1, ordering errs 0
Heater 1 is on, I-accum = 0.0
=== GCodes ===
Segments left: 0
Movement lock held by null
HTTP is idle in state(s) 0
Telnet is idle in state(s) 0
File is idle in state(s) 0
USB is idle in state(s) 0
Aux is idle in state(s) 0
Trigger is idle in state(s) 0
Queue is idle in state(s) 0
LCD is idle in state(s) 0
Daemon is idle in state(s) 0
Autopause is idle in state(s) 0
Code queue is empty
=== Network ===
Slowest loop: 79.93ms; fastest: 0.00ms
Responder states: HTTP(0) HTTP(0) HTTP(0) HTTP(0) FTP(0) Telnet(0), 0 sessions
HTTP sessions: 1 of 8
- WiFi -
Network state is active
WiFi module is connected to access point 
Failed messages: pending 0, notready 0, noresp 0
WiFi firmware version 1.26
WiFi MAC address 24:62:ab:04:1b:cb
WiFi Vcc 3.30, reset reason Turned on by main processor
WiFi flash size 4194304, free heap 23128
WiFi IP address 192.168.0.125
WiFi signal strength -67dBm, mode 802.11n, reconnections 0, sleep mode modem
Clock register 00002002
Socket states: 0 0 0 0 0 0 0 0

**Cura Log**
2022-08-02 12:15:12,665 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:     from . import DuetRRFPlugin, DuetRRFAction, DuetRRFSettings
2022-08-02 12:15:12,666 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:   File "C:\Users\User\AppData\Roaming\cura\5.0\plugins\DuetRRFPlugin\DuetRRFPlugin.py", line 3, in <module>
2022-08-02 12:15:12,667 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]:     from PyQt5.QtCore import Qt, QTimer
2022-08-02 12:15:12,667 - ERROR - [MainThread] UM.PluginRegistry._findPlugin [730]: ModuleNotFoundError: No m
[cura.log](https://github.com/Kriechi/Cura-DuetRRFPlugin/files/9240968/cura.log)
odule named 'PyQt5'
2022-08-02 12:15:12,670 - ERROR - [MainThread] UM.PluginRegistry.removeCorruptedPluginMessage [527]: Exception: Error loading plugin 

Hi , it seem like my python version is way back ....
Leaving it here for others to see ....

**Comment by Kriechi** [comment]
Thanks for reporting this! The correct fixes and the latest version were still sitting on the `next` branch.
I've now merged them back to the `master` branch.
