### ISSUE TITLE
cura5.3.1 

### ISSUE THREAD

**Issue by Olliftw** [Kriechi/Cura-DuetRRFPlugin#49]
is the duetRRFplugin not supported in 5.3.1? 
the plugin isnt showing eventouch already tryed reinstalling the pluggin etc.

grtz

**Comment by Kriechi** [comment]
Yes, the plugin supports Cura 5.3.1.
It is available in the Marketplace:
<img width="1283" alt="Screenshot 2023-04-22 at 16 32 46" src="https://user-images.githubusercontent.com/114300/233790942-1ace63bb-dd5e-41ae-b0b1-ffa0461d329b.png">

**Comment by Olliftw** [comment]
Wierd, cant get it to show up at the machine settings window, uninstalled the plugin, restarted cura and nothing, in marketplace it does show installed and up to date

Verstuurd vanaf mijn iPhone

Op 22 apr. 2023 om 16:35 heeft Thomas Kriechbaumer ***@***.***> het volgende geschreven:

﻿

Yes, the plugin supports Cura 5.3.1.
It is available in the Marketplace:
[Screenshot 2023-04-22 at 16 32 46]<https://user-images.githubusercontent.com/114300/233790942-1ace63bb-dd5e-41ae-b0b1-ffa0461d329b.png>

**Comment by Kriechi** [comment]
Please provide all the information from the bug report template: https://github.com/Kriechi/Cura-DuetRRFPlugin/issues/new?template=bug_report.md

**Comment by Olliftw** [comment]
[cura.log](https://github.com/Kriechi/Cura-DuetRRFPlugin/files/11301881/cura.log)

**Comment by Kriechi** [comment]
Odd - I see that the plugin seems to be installed (and also uninstalled) in the log, but I don't see it being loaded.
I suspect that your Cura settings and profile might be corrupt or in an inconsistent state.

Please try using a clean Cura profile: https://support.makerbot.com/s/article/1667337567843
