### ISSUE TITLE
update for Cura 5.4

### ISSUE THREAD

**Issue by chrizzor88** [Kriechi/Cura-DuetRRFPlugin#50]
Hey,

will there be an update for Cura 5.4.
Somehow the old version writes in my gcodes, even if i dont want to use the plugin.

Best Regards

**Comment by Kriechi** [comment]
Could you please elaborate on what the issue is you are seeing?
Please follow the Bug Report template and provide all the data so I can troubleshoot this with you:
https://github.com/Kriechi/Cura-DuetRRFPlugin/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=
