### ISSUE TITLE
enabling http auth causes crash

### ISSUE THREAD

**Issue by Thijskunst** [Kriechi/Cura-DuetRRFPlugin#51]
plugin causes cura to crash when sending file to a printer with http basic authentication enabled.

**To Reproduce**
1. load a 3d model
2. slice
3. click 'print on printername' or 'upload to printername'

**Expected behavior**
print starts on printer or file gets uploaded to printer

**Version Information**
 - Operating System: windows 11 pro 22H2
 - Cura Version: 5.4.0
 - Cura-DuetRRF Plugin Version and Installation: 1.2.9 installed via Marketplace
 - Duet RepRapFirmware Version:  RepRapFirmware for STM32F4 based Boards 3.5beta2+_103 (2023-02-11)
 Duet WiFi Server Version: 1.27-02S32-D

**error traceback**
Traceback (most recent call last):
  File "C:\Users\thijs\AppData\Roaming\cura\5.4\plugins\DuetRRFPlugin\DuetRRFPlugin\DuetRRFOutputDevice.py", line 234, in _onFilenameAccepted
    self._send('rr_connect',
  File "C:\Users\thijs\AppData\Roaming\cura\5.4\plugins\DuetRRFPlugin\DuetRRFPlugin\DuetRRFOutputDevice.py", line 137, in _send
    headers['Authorization'] = 'Basic ' + base64.b64encode(auth)
TypeError: can only concatenate str (not "bytes") to str

**Cura Log**

**Comment by Kriechi** [comment]
Thanks for reporting this @Thijskunst!

In your local file `C:\Users\thijs\AppData\Roaming\cura\5.4\plugins\DuetRRFPlugin\DuetRRFPlugin\DuetRRFOutputDevice.py` n line 137, please change the line to:

```python
headers['Authorization'] = 'Basic ' + base64.b64encode(auth).decode()
```

Save the file and restart Cura.

Please try this bug fix - if it works for you, I'll commit a fix and release a new version.

**Comment by Thijskunst** [comment]
thanks for your reply,

sorry for my slow reply. I was in the proces of changing the kinematics, so i wasnt able to print anything.
i tested it and the plugin works now without any issue.
