### ISSUE TITLE
Base off OctoPrintPlugin

### ISSUE THREAD

**Issue by cbusillo** [Kriechi/Cura-DuetRRFPlugin#6]
So I know its a completely different plugin, but have you looked at incorporating the features from OctoPrintPlugin?  It allows control of the printer and viewing of temps and even the webcam if available.  I started looking through the code but I think its too advanced for me =(.  I might try anyway if its not of any interest to you.  Thanks for the awesome plugin.  I do love it.

<img width="454" alt="screen shot 2018-03-15 at 1 34 52 pm" src="https://user-images.githubusercontent.com/1875516/37480527-d5854de0-2855-11e8-828f-693814a218ea.png">

**Comment by Kriechi** [comment]
DuetWebControl is much better than anything we could implement with Cura. 
For now I think this is way out of scope for this project - but if somebody likes to send a comprehensive PR - I'm open to look at it.
